services:
  mongodb:
    image: mongo:7-jammy
    container_name: geomood-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - geomood-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: geomood-backend
    ports:
      - "3000:3000"
    env_file:
      - ./packages/server/.env
    environment:
      DATABASE_URL: mongodb://mongodb:27017/geomoodmap
    volumes:
      - ./packages/server/src:/app/packages/server/src
    depends_on:
      - mongodb
    networks:
      - geomood-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.www
    container_name: geomood-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./packages/www/.env
    volumes:
      - ./packages/www/src:/app/packages/www/src
    depends_on:
      - backend
    networks:
      - geomood-network

networks:
  geomood-network:
    driver: bridge

volumes:
  mongodb_data:
